### ISSUE TITLE
Error: Cannot find module './index.scss'

### ISSUE THREAD

**Issue by ralphievolt** [intelllex/react-pdf#5]
I'm having trouble using this package.

This is the web console log error

`modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232 Uncaught Error: Cannot find module './index.scss'`

if I comment this `import ReactPDF from "@intelllex/react-pdf";`  the error goes away so this let me conclude that the error is is the code.

I'm using react

**Comment by trinhngocdieu** [comment]
@ralphievolt 
Can I know the react version and node version you're using?
Thanks!

**Comment by ralphievolt** [comment]
"react": "^16.13.1",

12.14.0

I'm using MeteorJs

**Comment by trinhngocdieu** [comment]
@ralphievolt got it, let me check, but just to make sure are you using the @intelllex/react-pdf version `1.0.16`?

**Comment by trinhngocdieu** [comment]
@ralphievolt I am not so sure why scss does not work in MeteorJS.
But I think you can add this package to support SCSS in your MeteorJS project:
`meteor add fourseven:scss`
(https://github.com/Meteor-Community-Packages/meteor-scss)
