### ISSUE TITLE
Why does it always open the default PDF

### ISSUE THREAD

**Issue by hector12free** [intelllex/react-pdf#6]
Why does it always open the [default pdf](https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf), even after I set a different url here:

```js
        <ReactPDF
            url="<my_PDF_url>"
            showProgressBar
            showToolbox
        />

```

**Comment by trinhngocdieu** [comment]
hi @hector12free , 
thank you for reporting the issue, there was on mistake while releasing the package.
I fixed the above issue on the latest version, please help me to update and check again.
Thanks!
